#!/bin/sh

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
# nvm use --silent

# The pre-push hook runs during git push, after the remote refs have been updated but before any objects have been transferred.
# It receives the name and location of the remote as parameters, and a list of to-be-updated refs through stdin.
# You can use it to validate a set of ref updates before a push occurs (a non-zero exit code will abort the push).

# rush change -v
