export * from './complements.interface';
export * from './comprobante.interface';
export * from './concepts.interface';
export * from './domiciolio.interface';
export * from './emisor.inteface';
export * from './impuestos.interface';
export * from './receptor.inteface';
export * from './tags.structure';
export * from './xmlCdfi.interface';
