import { OptionsPdf } from '../../src/types/options.pdf';
import { Generic } from '../../src/signati/generic';
import { TCreatedPdf } from 'pdfmake/build/pdfmake';
export declare class A117 extends Generic {
    private xml;
    private options;
    private docDefinition;
    constructor(xml: string, options?: OptionsPdf);
    getDocument(): Promise<TCreatedPdf>;
    private addLogo;
    private addFolio;
    private addEmisorData;
    private addDate;
    private addDetalles;
    private addReceptor;
    private addCatidad;
    private addImpuesto;
    private addNumberToLetter;
    private addCSDEmisor;
    private fechaTimbrado;
    private addCSDSat;
    private folioFiscal;
    private addSelloDgtEmisor;
    private addSelloDelSat;
    private addCadenaOriginal;
    private addFormaDePago;
    private addMetodoDePago;
    private addCuenta;
    private addMoneda;
    private addTipoComprobante;
    private addQr;
}
