name: development
on:
  push:
    branches:
      - next
      - beta
      - alpha
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: nelonoel/branch-name@v1.0.1
      - name: Cdfi
        uses: actions/checkout@v4

      - name: CFDI dependencies
        uses: ./.github/actions/cfdi
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Publish
        run: |
          echo $BRANCH_NAME
          rush publish --publish --tag $BRANCH_NAME --include-all --set-access-level=public --apply
          git commit -a -m 'npm(publish): new releases' || echo "No changes to commit"
          git push origin $BRANCH_NAME
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
