name: pre publish
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CFDI dependencies
        uses: ./.github/actions/cache

      - name: Additional Step
        run: echo "Executing additional step"
