name: prebublish
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cfdi
        uses: actions/checkout@v3

      - name: Schema
        uses: actions/checkout@v3
        with:
          repository: MisaelMa/cfdi-schema
          path: packages/cfdi/schema
          token: ${{ secrets.PAT_GITHUB }}


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Rush CLI
        run: npm install -g @microsoft/rush@5.82.1

      - name: Rush Update
        run: rush update

      - name: Script
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./common/scripts/github-actions.js')
            await script({github, context, core})
