name: pre publish
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cdfi
        uses: actions/checkout@v3

      - name: CFDI dependencies
        uses: ./.github/actions/cfdi
        with:
          token: ${{ secrets.PAT_GITHUB }}

      - name: Additional Step
        run: echo "Executing additional step"
