name: pre realease
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cdfi
        uses: actions/checkout@v3

      - uses: nelonoel/branch-name@v1.0.1
      - name: Publish
        run: |
          echo ${BRANCH_NAME}
