name: pre realease
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cdfi
        uses: actions/checkout@v3

      - name: Script
        uses: actions/github-script@v7
        with:
          debug: true
          script: |

            const script = require('./common/scripts/github-actions.js')
            await script({github, context, core})
