name: publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: schema
        uses: actions/checkout@v3
        with:
          repository: MisaelMa/cfdi-schema
          path: packages/cfdi/schema
          token: ${{ secrets.PAT_GITHUB }}

      - name: show
        run: |
         ls -la packages
         ls -la packages/cfdi
        working-directory: .  # Ubicación raíz del proyecto

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Rush CLI
        run: npm install -g @microsoft/rush@5.82.1

      - name: Rush Install
        uses: advancedcsg-open/actions-rush

      - name: Rush Update
        run: |
          git config user.name MisaelMa
          git config user.email amisael.amir.misael@gmail.com
          rush update
      - name: Script
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./common/scripts/github-actions.js')
            await script({github, context, core})
      - name: Publish
        run: |
          echo "amir"
          rush publish -p -b main --include-all --set-access-level=public
          git commit -a -m 'npm(publish): new releases' || echo "No changes to commit"
          git push
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
