name: publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone Dependency Repository
        run: |
          git config user.name MisaelMa
          git config user.email amisael.amir.misael@gmail.com
          git clone https://github.com/MisaelMa/cfdi-schema schema
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
        working-directory: .

      - name: Mover el repositorio clonado
        run: |
          mv schema packages/cfdi
        working-directory: .  # Ubicación raíz del proyecto

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Rush CLI
        run: npm install -g @microsoft/rush@5.50.0

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5

      - name: Rush Update
        run: |
          ls -la .
          rush update
      - name: Script
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./common/scripts/github-actions.js')
            await script({github, context, core})
      - name: Publish
        run: |
          echo "amir"
          rush publish -p -b main --include-all --set-access-level=public
          git commit -a -m 'npm(publish): new releases' || echo "No changes to commit"
          git push
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
