name: cfdi/xml
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Publish
        run: |
          git config user.name MisaelMa
          git config user.email amisael.amir.misael@gmail.com
          node common/scripts/install-run-rush.js install
          node common/scripts/install-run-rush.js update
          node common/scripts/install-run-rush.js version --version-policy cfdiXml --bump
          node common/scripts/install-run-rush.js publish -p -b main --version-policy cfdiXml --include-all --set-access-level=public --npm-auth-token=${{ secrets.NPM_TOKEN }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      #- name: Commit changes
      #  uses: EndBug/add-and-commit@v9
      #  with:
      #    author_name: MisaelMa
      #    author_email: amisael.amir.misael@gmail.com
      #    message: 'Your commit message'
      #    add: '*.'

      # - name: Install and Build
      #   run: |
      #     node common/scripts/install-run-rush.js install
      # - name: Publish
      #   run: |
      #     node common/scripts/install-run-rush.js version --version-policy cfdiXml --bump
      #     node common/scripts/install-run-rush.js publish -p -b main --version-policy cfdiXml --include-all --set-access-level=public
      #     node common/scripts/publish.js @cfdi/xml merge
      #     node common/scripts/publish.js @cfdi/xml apart
      #     git config user.name MisaelMa
      #     git config user.email amisael.amir.misael@gmail.com
      #     git commit -a -m 'Updated dists' || echo "No changes to commit"
      #     git push
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
